# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=200, verbose_name='\u680f\u76ee\u540d\u79f0')),
                ('column_url', models.CharField(max_length=200, verbose_name='\u680f\u76eeUrl')),
                ('column_icon', models.CharField(max_length=200, verbose_name='\u680f\u76eeIcon')),
                ('column_order', models.IntegerField(verbose_name='\u680f\u76ee\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u680f\u76ee\u7ba1\u7406',
                'verbose_name_plural': '\u680f\u76ee\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u540d\u79f0')),
                ('site_slogan', models.CharField(max_length=50, verbose_name='\u7f51\u7ad9\u5e7f\u544a\u8bed')),
                ('site_author', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u4f5c\u8005')),
                ('site_keywords', models.CharField(max_length=200, verbose_name='\u7f51\u7ad9\u5173\u952e\u8bcd')),
                ('site_description', models.TextField(verbose_name='\u7f51\u7ad9\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u4fe1\u606f\u7ba1\u7406',
                'verbose_name_plural': '\u7f51\u7ad9\u4fe1\u606f\u7ba1\u7406',
            },
        ),
    ]
