# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u680f\u76ee\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='website',
            name='site_copyright',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u7248\u6743\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='column',
            name='column_icon',
            field=models.CharField(max_length=100, verbose_name='\u680f\u76eeIcon'),
        ),
        migrations.AlterField(
            model_name='column',
            name='column_name',
            field=models.CharField(max_length=30, verbose_name='\u680f\u76ee\u540d\u79f0'),
        ),
    ]
