# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20160320_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_time', models.CharField(blank=True, max_length=50, verbose_name='\u65b0\u95fb\u65f6\u95f4')),
                ('news_title', models.CharField(blank=True, max_length=200, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u52a8\u6001\u7ba1\u7406',
                'verbose_name_plural': '\u65b0\u95fb\u52a8\u6001\u7ba1\u7406',
            },
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'managed': False, 'verbose_name': '\u7f51\u7ad9\u4fe1\u606f\u7ba1\u7406', 'verbose_name_plural': '\u7f51\u7ad9\u4fe1\u606f\u7ba1\u7406'},
        ),
    ]
