# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20160405_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_status',
            field=models.IntegerField(verbose_name='\u680f\u76ee\u72b6\u6001'),
        ),
    ]
