# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20160430_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_search',
            field=models.IntegerField(default=0, verbose_name='\u641c\u7d22\u72b6\u6001'),
        ),
    ]
