# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_column_column_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(blank=True, max_length=200, verbose_name='\u94fe\u63a5\u540d\u79f0')),
                ('linkurl', models.CharField(blank=True, max_length=200, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Website')),
            ],
            options={
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5\u7ba1\u7406',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5\u7ba1\u7406',
            },
        ),
    ]
