# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_friendlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30, verbose_name='\u83dc\u5355\u540d\u79f0')),
                ('menu_url', models.CharField(max_length=200, verbose_name='\u83dc\u5355Url')),
                ('menu_order', models.IntegerField(default=0, verbose_name='\u83dc\u5355\u6392\u5e8f')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Column')),
            ],
            options={
                'verbose_name': '\u4e8c\u7ea7\u83dc\u5355\u7ba1\u7406',
                'verbose_name_plural': '\u4e8c\u7ea7\u83dc\u5355\u7ba1\u7406',
            },
        ),
    ]
