# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjadminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u540d\u79f0')),
                ('site_author', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u4f5c\u8005')),
                ('site_keywords', models.CharField(max_length=200, verbose_name='\u7f51\u7ad9\u5173\u952e\u8bcd')),
                ('site_description', models.TextField(verbose_name='\u7f51\u7ad9\u63cf\u8ff0')),
                ('site_copyright', models.CharField(blank=True, max_length=200, verbose_name='\u7248\u6743\u4fe1\u606f')),
                ('site_license', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6848\u53f7')),
                ('site_email', models.CharField(blank=True, max_length=45, verbose_name='\u90ae\u7bb1')),
                ('site_phone', models.CharField(blank=True, max_length=200, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
            ],
            options={
                'db_table': 'djadmin_info',
                'verbose_name': '\u7f51\u7ad9\u540e\u53f0\u4fe1\u606f\u7ba1\u7406',
                'verbose_name_plural': '\u7f51\u7ad9\u540e\u53f0\u4fe1\u606f\u7ba1\u7406',
            },
        ),
    ]
