# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=200, verbose_name='\u94fe\u63a5\u540d\u79f0')),
                ('link_url', models.CharField(blank=True, max_length=200, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('link_order', models.IntegerField(default=0, verbose_name='\u680f\u76ee\u6392\u5e8f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'djadmin_friend_links',
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5\u7ba1\u7406',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u540d\u79f0')),
                ('site_slogan', models.CharField(max_length=50, verbose_name='\u7f51\u7ad9\u5e7f\u544a\u8bed')),
                ('site_author', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u4f5c\u8005')),
                ('site_keywords', models.CharField(max_length=200, verbose_name='\u7f51\u7ad9\u5173\u952e\u8bcd')),
                ('site_description', models.TextField(verbose_name='\u7f51\u7ad9\u63cf\u8ff0')),
                ('site_copyright', models.CharField(blank=True, max_length=200, verbose_name='\u7248\u6743\u4fe1\u606f')),
                ('site_license', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6848\u53f7')),
                ('site_declaration', models.TextField(blank=True, verbose_name='\u8d1f\u8d23\u58f0\u660e')),
                ('site_address', models.CharField(blank=True, max_length=200, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('site_zip', models.CharField(blank=True, max_length=45, verbose_name='\u90ae\u7f16')),
                ('site_email', models.CharField(blank=True, max_length=45, verbose_name='\u90ae\u7bb1')),
                ('site_phone', models.CharField(blank=True, max_length=200, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
            ],
            options={
                'db_table': 'djadmin_site_info',
                'verbose_name': '\u7f51\u7ad9\u4fe1\u606f\u7ba1\u7406',
                'verbose_name_plural': '\u7f51\u7ad9\u4fe1\u606f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SiteNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_time', models.CharField(blank=True, max_length=50, verbose_name='\u65b0\u95fb\u65f6\u95f4')),
                ('news_title', models.CharField(blank=True, max_length=200, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'djadmin_site_news',
                'verbose_name': '\u65b0\u95fb\u52a8\u6001\u7ba1\u7406',
                'verbose_name_plural': '\u65b0\u95fb\u52a8\u6001\u7ba1\u7406',
            },
        ),
        migrations.DeleteModel(
            name='DjadminInfo',
        ),
    ]
