# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0002_auto_20161015_1703'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendlinks',
            table='django_friend_links',
        ),
        migrations.AlterModelTable(
            name='siteinfo',
            table='django_site_info',
        ),
        migrations.AlterModelTable(
            name='sitenews',
            table='django_site_news',
        ),
    ]
