# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0003_auto_20161015_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendLinks',
        ),
        migrations.DeleteModel(
            name='SiteNews',
        ),
    ]
