# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0005_menuinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='\u83dc\u5355\u9879\u540d\u79f0')),
                ('item_link', models.CharField(max_length=255, verbose_name='\u83dc\u5355\u9879\u94fe\u63a5')),
                ('item_order', models.IntegerField(null=True, verbose_name='\u83dc\u5355\u9879\u6392\u5e8f')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'django_menu_item',
                'verbose_name': '\u83dc\u5355\u9879\u7ba1\u7406',
                'verbose_name_plural': '\u83dc\u5355\u9879\u7ba1\u7406',
            },
        ),
        migrations.AlterModelOptions(
            name='menuinfo',
            options={'verbose_name': '\u83dc\u5355\u7ba1\u7406', 'verbose_name_plural': '\u83dc\u5355\u7ba1\u7406'},
        ),
        migrations.RemoveField(
            model_name='menuinfo',
            name='menu_link',
        ),
        migrations.RemoveField(
            model_name='menuinfo',
            name='menu_pid',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djadmin.MenuInfo', verbose_name='\u4e0a\u7ea7\u7c7b\u76ee'),
        ),
    ]
