# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0006_auto_20161015_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_address',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_declaration',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_zip',
        ),
    ]
