# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='/static/avatar/default.gif', max_length=200, verbose_name='\u5934\u50cf\u5730\u5740'),
        ),
    ]
