# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerShoppingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='\u5546\u54c1\u6765\u6e90')),
                ('srcid', models.CharField(blank=True, max_length=255, verbose_name='\u5546\u54c1\u7f16\u53f7')),
                ('srclink', models.CharField(blank=True, max_length=255, verbose_name='\u5546\u54c1URL')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('price', models.FloatField(blank=True, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('starttime', models.DateTimeField(null=True, verbose_name='\u4e0a\u67b6\u65f6\u95f4')),
                ('finishtime', models.DateTimeField(null=True, verbose_name='\u4e0b\u4ef7\u65f6\u95f4')),
                ('viewnum', models.IntegerField(blank=True, default=0, verbose_name='\u6d4f\u89c8')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'crawler_shopping_info',
                'verbose_name': '\u5546\u54c1\u4fe1\u606f',
                'verbose_name_plural': '\u5546\u54c1\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='CrawlerShoppingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('pid', models.IntegerField(null=True, verbose_name='\u4e0a\u7ea7\u5206\u7c7b')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'crawler_shopping_type',
                'verbose_name': '\u5546\u54c1\u7c7b\u76ee',
                'verbose_name_plural': '\u5546\u54c1\u7c7b\u76ee',
            },
        ),
        migrations.AddField(
            model_name='crawlershoppinginfo',
            name='shoppingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.CrawlerShoppingType', verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
    ]
