# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlershoppinginfo',
            name='imglink',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u56fe\u7247URL'),
        ),
    ]
